package com.example.virgo.model.appointment

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Info
import androidx.compose.ui.graphics.vector.ImageVector

enum class Department(val id: Int, val title: String, val icon: ImageVector) {
    ALL_DEPARTMENTS(0, "All departments", Icons.Filled.Info),
    NUTRITION_AND_DIETETICS(1, "Nutrition and Dietetics", Icons.Filled.Info),
    PSYCHOLOGICAL_COUNSELING(2, "Psychological Counseling", Icons.Filled.Info),
    OPHTHALMIC_REFRACTION(3, "Ophthalmic Refraction", Icons.Filled.Info),
    GENERAL_INTERNAL_MEDICINE(4, "General Internal Medicine", Icons.Filled.Info),
    NEUROSURGERY(5, "Neurosurgery", Icons.Filled.Info),
    GENERAL_SURGERY(6, "General Surgery", Icons.Filled.Info),
    VACCINATION(7, "Vaccination", Icons.Filled.Info),
    DIABETES(8, "Diabetes", Icons.Filled.Info),
    ANESTHESIA_PAIN_MANAGEMENT(9, "Anesthesia - Pain Management", Icons.Filled.Info),
    NEUROLOGY(10, "Neurology", Icons.Filled.Info),
    PATHOLOGY(11, "Pathology", Icons.Filled.Info),
    GERIATRICS(12, "Geriatrics", Icons.Filled.Info),
    RADIOLOGY(13, "Radiology", Icons.Filled.Info),
    IMMUNOLOGY(14, "Immunology", Icons.Filled.Info),
    MUSCULOSKELETAL(15, "Musculoskeletal", Icons.Filled.Info),
    SPORTS_SCIENCE(16, "Sports Science", Icons.Filled.Info),
    PSYCHOLOGY(17, "Psychology", Icons.Filled.Info),
    PHYSICAL_THERAPY(18, "Physical Therapy", Icons.Filled.Info),
    ORTHOPEDICS(19, "Orthopedics", Icons.Filled.Info),
    PSYCHIATRY(20, "Psychiatry", Icons.Filled.Info),
    HEMATOLOGY(21, "Hematology", Icons.Filled.Info),
    ONCOLOGY(22, "Oncology", Icons.Filled.Info),
    PULMONOLOGY(23, "Pulmonology", Icons.Filled.Info),
    UROLOGY(24, "Urology", Icons.Filled.Info),
    NEPHROLOGY(25, "Nephrology", Icons.Filled.Info),
    RHEUMATOLOGY(26, "Rheumatology", Icons.Filled.Info),
    ENDOCRINOLOGY(27, "Endocrinology", Icons.Filled.Info),
    GENERAL_MEDICINE(28, "General Medicine", Icons.Filled.Info),
    DENTISTRY(29, "Dentistry", Icons.Filled.Info),
    DERMATOLOGY(30, "Dermatology", Icons.Filled.Info),
    OPHTHALMOLOGY(31, "Ophthalmology", Icons.Filled.Info),
    OBSTETRICS_AND_GYNECOLOGY(32, "Obstetrics and Gynecology", Icons.Filled.Info),
    CHIROPRACTIC_NEUROLOGY(33, "Chiropractic Neurology", Icons.Filled.Info),
    PEDIATRICS(34, "Pediatrics", Icons.Filled.Info),
    ENT(35, "ENT (Ear, Nose, and Throat)", Icons.Filled.Info),
    GASTROENTEROLOGY(36, "Gastroenterology", Icons.Filled.Info),
    CARDIOLOGY(37, "Cardiology", Icons.Filled.Info),
    INFECTIOUS_DISEASES(38, "Infectious Diseases", Icons.Filled.Info),
    HEPATOBILIARY(39, "Hepatobiliary", Icons.Filled.Info),
    RESPIRATORY_THERAPY(40, "Respiratory Therapy", Icons.Filled.Info),
    FOOT_SPECIALTY(41, "Foot Specialty", Icons.Filled.Info),
    REHABILITATION_MEDICINE(42, "Rehabilitation Medicine", Icons.Filled.Info),
    TRADITIONAL_MEDICINE(43, "Traditional Medicine", Icons.Filled.Info),
    OBESITY_SPECIALTY(44, "Obesity Specialty", Icons.Filled.Info),
    SLEEP_MEDICINE(45, "Sleep Medicine", Icons.Filled.Info),
    SEXOLOGY(46, "Sexology", Icons.Filled.Info),
    AESTHETIC_SURGERY(47, "Aesthetic Surgery", Icons.Filled.Info),
    ANDROLOGY(48, "Andrology", Icons.Filled.Info),
}

